# Github
This is a Hello World.


In [1]:
import numpy as np
L = [1,2,3]
A = np.array(L)

for e in L:
    print(e)
for e in A:
    print(e)

1
2
3
1
2
3


In [2]:
L.append(4)
print("List append {}".format(L))
L.append(4)
print("List append with `.append` in place {}".format(L))

L = L + [5]
print("List append with '+' {}".format(L))

B = np.array([5,6,7])
print("Numpy append {}".format(np.append(A, B)))

List append [1, 2, 3, 4]
List append with `.append` in place [1, 2, 3, 4, 4]
List append with '+' [1, 2, 3, 4, 4, 5]
Numpy append [1 2 3 5 6 7]


In [13]:
L2 = []
for e in L:
    L2.append(e + e)
print("List addtion `+` {}".format(L2))
print("Numpy addition `+` {}".format(A + A))
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Numpy addition 1D:`+` {}".format(M))
print("Numpy addition 2D:`+` {}".format(M + M))
print("Numpy element-wise multiplication {}".format(M * M))
print("Numpy element-wise integer division {}".format(M /2))
M = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
print(M/2)
print("Scalar multiplication {}".format(A * 2))
print("Squaring {}".format(A**2))
print("Exponentation {}".format(np.exp(A)))
print("Log {}".format(np.log(A)))
print("Square root {}".format(np.sqrt(A)))

List addtion `+` [2, 4, 6, 8, 8, 10]
Numpy addition `+` [2 4 6]
Numpy addition 1D:`+` [[1 2 3]
 [4 5 6]
 [7 8 9]]
Numpy addition 2D:`+` [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Numpy element-wise multiplication [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Numpy element-wise integer division [[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
Scalar multiplication [2 4 6]
Squaring [1 4 9]
Exponentation [ 2.71828183  7.3890561  20.08553692]
Log [0.         0.69314718 1.09861229]
Square root [1.         1.41421356 1.73205081]


In [14]:
print("Multiplication list: {}".format(2 * L))
L2 = []
for e in L:
    L2.append(e/2.0)
print(L2)

Multiplication list: [1, 2, 3, 4, 4, 5, 1, 2, 3, 4, 4, 5]
[0.5, 1.0, 1.5, 2.0, 2.0, 2.5]


In [15]:
a1 = np.array([6,2,3,4,5])
a2 = np.array([5,4,3,2,1])
dot_product = 0
for e1, e2 in zip(a1, a2):
    dot_product += e1 * e2
print("The dot product is {}".format(dot_product))

The dot product is 60


In [16]:
approach_1 = np.sum(a1 * a2)
approach_2 = (a1 * a2).sum()
print("Function Approach 1: numpy method: {}".format(approach_1))
print("Function Approach 2: `sum` as an instance method {}" .format(approach_2))

Function Approach 1: numpy method: 60
Function Approach 2: `sum` as an instance method 60


In [17]:
builtin_1 = np.dot(a1, a2)
builtin_2 =  a1.dot(a2)
print("Builtin Approach 1: {}".format(builtin_1))
print("Builtin Approach 2: instance method {}".format(builtin_2))      

Builtin Approach 1: 60
Builtin Approach 2: instance method 60


In [19]:
a1Mag = np.sqrt(a1.dot(a1)) ; a2Mag = np.sqrt(a2.dot(a2))
print("Direct calculation of L2 norm {}".format(a1Mag))
a1MagM2 = np.linalg.norm(a1) ; a2MagM2 = np.linalg.norm(a2)
print("`lingalg` calculation of L2 norm {}".format(a1MagM2))

Direct calculation of L2 norm 9.486832980505138
`lingalg` calculation of L2 norm 9.486832980505138


In [20]:
cosAngle = a1.dot(a2) / (a1Mag * a2Mag)
print("Angle (degrees) from dot product {}".format(cosAngle))
angle = np.arccos(cosAngle)
print("Angle (radians) from dot product {}".format(angle))

Angle (degrees) from dot product 0.8528028654224418
Angle (radians) from dot product 0.5494672447576273


In [ ]:
import numpy as np
from datetime import datetime

def loop_dot_product(a1, a2):
    dot_product = 0
    